### ISSUE TITLE
Add an & feature

### ISSUE THREAD

**Issue by T0rchik** [Asmor/5e-monsters#127]
Not sure if this is already implemented but i just thought it would be nice to be able to search for more than one category. Say if I wanted to to make a random encounter involving both Kobolds and Dragon Wyrms, I could search for "Kobolds & Wyrms". Then I could simply press "Random Encounter Hard" instead of having to continually search wyrm then kobold while trying to get the balance right.

You might be able to do this by adding something like this in the function SortAndFilterMonsters(monsterLib):

```
requested = input.split('&');
for (u = 0; u < requested.length; u++){
	new = requested[u];
	for ( i = 0; i < new.length; i++ ) {
		if ( monsterLib.checkMonster(input[i], filters) ) {
			output.push(input[i]);
		}
	}
}
```

**Comment by Asmor** [comment]
I've added the ability to use regular expressions, which will allow you to do what you want (and way, way, way more).

To do a regex search, start your search with a `/` (otherwise it will be treated as a normal search).

To do multiple finds, just separate your terms with pipes (`|`). For example, to find kobolds and wryms, you could search for `/kobold|wyrm`

This is a full JavaScript regex, though, so there's a lot more you can do. One simple example is using `\b` for word boundaries, which lets you find dogs and cats without catoblepas and dogmoles also showing up: `/\bcat\b|\bdog\b`

**Comment by T0rchik** [comment]
This is pretty useful, thanks. It should probably be put in the FAQ so that others can find it as well.

**Comment by Asmor** [comment]
Yeah... I posted on reddit about it in /r/asmor, /r/dnd, and /r/dndnext. I probably will add it to the FAQ at some point, but I'd prefer to have a better way of informing people and I'm not really sure what that looks like yet.

**Comment by jbarzilai** [comment]
The best way to inform people, in my opinion, is to build it into the UI
somehow. A button that shows help in a dialog is the simplest. A drop-down
or dialog that assists in building the regex is more ambitious. Example of
this is Gmail's search drop down that gives a ton of power.
