### ISSUE TITLE
Can't get the sheet checker to load my sheets

### ISSUE THREAD

**Issue by JFDow** [Asmor/5e-monsters#174]
Hey, I thought I might put together a couple sheets of monsters for Sprouting Chaos and Strongholds & Followers, anyway I think I'm doing something wrong because they can't load in the sheet checker

https://docs.google.com/spreadsheets/d/1x8pigUSU5IJ1304m-RVC1rNMVbxCzDGn7wOTac5Im5E/edit?usp=sharing

https://docs.google.com/spreadsheets/d/1Llha2UsVF-bLm3HhPiM3N_AejAs4gB0CoCIABCnYG9o/edit?usp=sharing

**Comment by Asmor** [comment]
The most likely explanation is that they haven't been published. Go to file -> publish to the web. If there's a green button there that says "publish", click it (don't change any values, just click the button).

Also, it looks like you've made it so that these sheets are editable by anyone. If you're going to share them with others, I'd strongly recommend changing the sharing settings so other people can only view and not edit.

**Comment by JFDow** [comment]
Thanks, got it all working
