### ISSUE TITLE
jQuery source is blocked from loading in Chrome

### ISSUE THREAD

**Issue by chrisbloom7** [Asmor/5e-monsters#210]
In Chrome Version 89.0.4389.90, http://kobold.club/fight/#/encounter-builder logs an error in the console `Failed to find a valid digest in the 'integrity' attribute for resource 'https://code.jquery.com/jquery-3.1.1.js' with computed SHA-256 integrity 'hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8='. The resource has been blocked.` This causes several UI elements to not work as expected.

**Comment by Asmor** [comment]
That means that the version of jQuery that you received doesn't match what was expected. It's working fine for me (and with exact same version of Chrome down to the `.90`), and this hasn't been changed in _years_, so either something got corrupted in your request/cache or someone's modifying the code that's coming down the pipe at you.

For example, I know in the past some ISPs (e.g. Comcast) have performed man-in-the-middle attacks against their own customers both by modifying responses on the fly and by fucking with DNS so you get routed through their own proxy. Hypothetically if they were doing that to modify the content of the jQuery script, it would change the hash and you'd get the error you saw.

It's a lot more likely that you just got a bad response and it's cached. Maybe there were network issues and you got served a Cloudflare error page instead of the JS file.

I'd recommend clearing your cache and trying again. If it still persists and you're using KFC on http, you might consider switching to https; that should prevent any 3rd parties from tampering with the contents of responses.

**Comment by chrisbloom7** [comment]
Thanks for the suggestion. Looks like AdBlock was serving a cached version. I disabled the extension, cleared cache, and refreshed the page and it's working again.

**Comment by Asmor** [comment]
That's very strange. This is a specific version of jQuery, there's no reason the file should _ever_ change. You might want to look into your ad blocker, just check around to make sure they haven't been compromised.
