### ISSUE TITLE
Add a Open Source Friendly License

### ISSUE THREAD

**Issue by 10leej** [Asmor/5e-monsters#220]
This will allow the project to continue as it's a great tool. I'd rather not make a new tool and repeat the same efforts the developers here went though.

**Comment by TechnologyClassroom** [comment]
package.json says MIT.  A `LICENSE` file would make this more obvious and appear in the About section in the first pageview.  If you would like me to make a PR for this, I could help with that.

**Comment by Asmor** [comment]
@TechnologyClassroom Go for it.

I view open source licenses much like health insurance in the US; an evil necessary only because of an even stupider and more evil situation. Copyright _might_ have been a good idea hundreds of years ago when it was first created, but it's actively harmful in the modern world and further software should _never_ have been subject to copyright law in the first place.

And that's my political rant for the afternoon. Carry on.

**Comment by TechnologyClassroom** [comment]
I do not understand how open source is a necessary evil, but I do agree that copyright is actively harmful.
