### ISSUE TITLE
Monster payload on Improved Initiative integration is misusing the Initiative Modifier field

### ISSUE THREAD

**Issue by cynicaloptimist** [Asmor/5e-monsters#43]
The initiative modifier field in Improved Initiative is designed for miscellaneous modifiers that are applied on top of dexterity modifier, such as the benefit from the Alert feat.

Kobold Fight Club's monster data only includes the final initiative modifier; it doesn't contain ability scores to disambiguate a boosted initiative modifier.

Suggested fix: don't include initiative bonus in the payload for monsters posted to Improved Initiative. Should be an easy fix: remove [integration.service.js:95](https://github.com/Asmor/5e-monsters/blob/ead82fe169e80e0f820333ce8f5dcc6a0be9d2dd/app/services/integration.service.js#L95). If this is unacceptable, I can update the endpoint to accept a 'final initiative' field.

See https://github.com/cynicaloptimist/improved-initiative/issues/87

**Comment by Asmor** [comment]
Just to be clear, your suggested fix is to not send an initiative modifier at all. Is that correct?

It wouldn't be feasible for me to go through all the monsters to separate out their base modifiers from any bonii, so that's off the table. I could remove that from the payload simply enough, but presumably that means any monsters we send over that aren't in your DB are going to be without initiative scores at all.

Honestly, I don't really have a horse in this race. I prefer running my initiative on paper. I'm perfectly happy to rip that out, as it would definitely be the simplest solution. I guess the question is how much trouble would it be for you to implement the "final initiative" field, and more importantly is that something you _want_ to do?

**Comment by cynicaloptimist** [comment]
No problem- I thought about it and I think the final initiative option is
probably the best. I'll submit a PR for this after I deploy an update.
