### ISSUE TITLE
The random button ignores the CR filters

### ISSUE THREAD

**Issue by ghost** [Asmor/5e-monsters#77]
It doesn't matter what minimal value I put on the CR min filter, the random button keeps generating creatures with levels below it.

To demonstrate: just put any number on the CR min filter and press the random button, then look at the CR of the generated creatures.

**Comment by Asmor** [comment]
CR checks are explicitly disabled for random encounter generation. This will not be changed.

**Comment by ghost** [comment]
Why is that?

**Comment by Asmor** [comment]
If this matters so much to you, it's very simple to change. Just fork this repo and change skipCrCheck to false on this line:

https://github.com/Asmor/5e-monsters/blob/master/app/services/randomencounter.service.js#L108

**Comment by jbarzilai** [comment]
I think the simple answer is that in order for the algorithm for random
encounters to work, it's hard to limit to a specific CR range.

The nature of generating a level appropriate encounter usually limits the
CR to generally the right spot.

What use case are you trying to provide for where you'd like to limit the
CR?

**Comment by ghost** [comment]
It was just that having monsters above a certain CR would be great, I'll do what @Asmor said.

Thanks for all the help!

**Comment by chisaipete** [comment]
If I may butt in: @MrLabRat keep in mind that when building encounters
there are many ways of balancing them and CR should really only be used as
a rough estimate.  None of the metrics we as DMs use to balance encounters
is going to be 100% accurate all the time due to a multitude of factors
beyond our control (DM pulling punches, PC abilities and resource loadout,
battle environment factors, etc).  In this particular tool, when generating
random encounters, it seeks to match the requested difficulty level
dependent on the SRD/DMG encounter balancing rules with respect to the
level of difficulty requested and calculated by party level, and then also
respect the list of monsters that you've filtered by source, terrain,
search string, etc.  Now, what may be more interesting would be more knobs
to tweak which encounter balancing rules are used to choose monsters.
