### ISSUE TITLE
Alignment Search Confuses "Any Alignment" with "any"

### ISSUE THREAD

**Issue by tomaskroth** [Asmor/5e-monsters#90]
When you set no filter for Alignment (any alignment option) all alignments appear, as expected.
When you change the combo to "any" I expected to show only creatures with "any", but it shows all alignments.

![2017-12-01_17-45-06](https://user-images.githubusercontent.com/9924355/33500320-8afbde0c-d6bf-11e7-98a3-699737b5ad1a.png)

![2017-12-01_17-45-48](https://user-images.githubusercontent.com/9924355/33500317-8aca4658-d6bf-11e7-9eb6-b501c1556f3d.png)

**Comment by Asmor** [comment]
This is a bit confusing, but it's accurate.

The idea for the alignment search is to find all monsters which _could_ be that alignment. So if you're searching for "chaotic evil", it will find all monsters which are chaotic evil, as well as all monsters that are "any chaotic" or "any evil", monsters with "any", etc.

This behavior makes more sense when you consider what happens if you search for "any chaotic". In this case, it shows monsters like the Cambion which have "any evil", because a Cambion could be chaotic evil, which matches the search for "any chaotic" monster.

So bringing it back, searching for "any" matches any monster that can have an alignment. In other words, everything except for unaligned monsters.
